# Generated by Django 5.1.2 on 2024-12-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_member_id_member_custom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='custom_id',
            new_name='id',
        ),
    ]
